use_default_settings: true

server:
  secret_key: "zee-noiz-tech-secret-change-me"
  limiter: false

ui:
  static_use_hash: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
    disabled: false
  - name: wikipedia
    engine: wikipedia
    shortcut: w
    disabled: false
